-- Configure after storing the URL and secret in Vault. See README; placeholders deliberately fail closed.
-- select vault.create_secret('https://api.example.com', 'certificate_api_url');
-- select vault.create_secret('replace-with-rotating-secret', 'certificate_cleanup_secret');
-- select cron.schedule('purge-expired-certificates', '17 * * * *', $$
--   select net.http_post(
--     url := (select decrypted_secret from vault.decrypted_secrets where name='certificate_api_url') || '/api/v1/internal/jobs/purge-expired-certificates',
--     headers := jsonb_build_object('content-type','application/json','x-internal-job-secret',(select decrypted_secret from vault.decrypted_secrets where name='certificate_cleanup_secret')),
--     body := '{}'::jsonb
--   );
-- $$);
